import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./Components/Sidebar/Sidebar";
import GlobalStyleProvider from "./Providers/GlobalStyleProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  { children, }: Readonly<{children: React.ReactNode;}>
){
  return (
    <html lang="en">
      <body>
        <GlobalStyleProvider>
          <Sidebar />
          {children}
        </GlobalStyleProvider>
      </body>
    </html>
  );
}
